services:
  backend:
    image: alpine
    command: ["sleep", "infinity"]
    volumes:
      - ./data:/data

  dirsizer:
    image: ghcr.io/mtzanidakis/dirsizer
    container_name: dirsizer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DIRECTORY: /data
      MAIL_FROM: dirsizer@localhost
      MAIL_TO: root
      SMTP_SERVER: host.docker.internal:25
      THRESHOLD: 1G
    volumes:
      - ./data:/data:ro
